e2e_controller systemd script fix for rootfs

diff --git a/service_chroot/e2e_controller/stop b/service_chroot/e2e_controller/stop
--- a/service_chroot/e2e_controller/stop
+++ b/service_chroot/e2e_controller/stop
@@ -1,11 +1,12 @@
 #!/bin/bash
 if [ -z "$E2E_TOPOLOGY_FILE" ] || [ ! -f "$E2E_TOPOLOGY_FILE" ]; then
-  echo "E2E_TOPOLOGY_FILE not set or not found"
-  exit 1
+	echo "E2E_TOPOLOGY_FILE not set or not found"
+	exit 1
 fi
+E2E_ROOTFS="$1"
 if [ -z "$E2E_ROOTFS" ] || [ ! -d "$E2E_ROOTFS" ]; then
-  echo "E2E_ROOTFS not set or not found"
-  exit 1
+	echo "You must specify the E2E rootfs to stop as the first parameter"
+	exit 1
 fi
 # copy topology file from chroot
 cp -v "${E2E_ROOTFS}/etc/e2e_config/topology.conf" "$E2E_TOPOLOGY_FILE"
